-- Table: public.passwordhashalgo

-- DROP TABLE public.passwordhashalgo;

CREATE TABLE public.passwordhashalgo
(
    algo_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    algo_name character varying(255) COLLATE pg_catalog."default",
    hash_algo character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT passwordhashalgo_pkey PRIMARY KEY (algo_id)
)

TABLESPACE pg_default;

ALTER TABLE public.passwordhashalgo
    OWNER to postgres;
-- Table: public.users

-- DROP TABLE public.users;

CREATE TABLE public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    email_address character varying(255) COLLATE pg_catalog."default",
    first_name character varying(255) COLLATE pg_catalog."default",
    last_name character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    password_algo_algo_id bigint,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT fkiye23algv6gsed6cpwrajxr1t FOREIGN KEY (password_algo_algo_id)
        REFERENCES public.passwordhashalgo (algo_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE public.users
    OWNER to postgres;

